In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
super_bowl_file = "Resources/Super_Bowl.csv"
super_bowl_df = pd.read_csv(super_bowl_file)
super_bowl_df.head()

,Date,SB,Attendance,QB Winner,Coach Winner,Winner,Winning Pts,QB Loser,Coach Loser,Loser,...,City,State,Point Difference,Referee,Umpire,Head Linesman,Line Judge,Field Judge,Back Judge,Side Judge
0,15-Jan-67,I,61946,Bart Starr,Vince Lombardi,Green Bay Packers,35,Len Dawson,Hank Stram,Kansas City Chiefs,...,Los Angeles,California,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14-Jan-68,II,75546,Bart Starr,Vince Lombardi,Green Bay Packers,33,Daryle Lamonica,John Rauch,Oakland Raiders,...,Miami,Florida,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12-Jan-69,III,75389,Joe Namath,Weeb Ewbank,New York Jets,16,"Earl Morrall, Johnny Unitas",Don Shula,Baltimore Colts,...,Miami,Florida,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11-Jan-70,IV,80562,"Len Dawson, Mike Livingston",Hank Stram,Kansas City Chiefs,23,Joe Kapp,Bud Grant,Minnesota Vikings,...,New Orleans,Louisiana,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17-Jan-71,V,79204,"Earl Morrall , Johnny Unitas",Don McCafferty,Baltimore Colts,16,Craig Morton,Tom Landry,Dallas Cowboys,...,Miami,Florida,3,Norm Schachter,Paul Trepinski,Ed Marion,Jack Fette,Fritz Graf,Hugh Gamber,NaN

In [3]:
# Clean the data by dropping duplicates and setting the index
# super_bowl_df.set_index("SB", inplace=True)

super_bowl_df.head()

,Date,SB,Attendance,QB Winner,Coach Winner,Winner,Winning Pts,QB Loser,Coach Loser,Loser,...,City,State,Point Difference,Referee,Umpire,Head Linesman,Line Judge,Field Judge,Back Judge,Side Judge
0,15-Jan-67,I,61946,Bart Starr,Vince Lombardi,Green Bay Packers,35,Len Dawson,Hank Stram,Kansas City Chiefs,...,Los Angeles,California,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14-Jan-68,II,75546,Bart Starr,Vince Lombardi,Green Bay Packers,33,Daryle Lamonica,John Rauch,Oakland Raiders,...,Miami,Florida,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12-Jan-69,III,75389,Joe Namath,Weeb Ewbank,New York Jets,16,"Earl Morrall, Johnny Unitas",Don Shula,Baltimore Colts,...,Miami,Florida,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11-Jan-70,IV,80562,"Len Dawson, Mike Livingston",Hank Stram,Kansas City Chiefs,23,Joe Kapp,Bud Grant,Minnesota Vikings,...,New Orleans,Louisiana,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17-Jan-71,V,79204,"Earl Morrall , Johnny Unitas",Don McCafferty,Baltimore Colts,16,Craig Morton,Tom Landry,Dallas Cowboys,...,Miami,Florida,3,Norm Schachter,Paul Trepinski,Ed Marion,Jack Fette,Fritz Graf,Hugh Gamber,NaN

In [4]:
cleaned_sb_df = super_bowl_df.drop(["Date", "QB  Winner", "Coach Winner", "Coach Loser", "Referee", "Umpire", "Head Linesman", "Line Judge", "Field Judge", "Back Judge", "Side Judge", "Point Difference", "QB Loser"], axis =1)
cleaned_sb_df = cleaned_sb_df[["SB", "Attendance", "Winner", "Winning Pts", "Loser", "Losing Pts", "MVP", "Stadium", "City", "State"]]
cleaned_sb_df = cleaned_sb_df.rename(columns={"Attendance":"attendance", "Winner":"winner", "Winning Pts":"winning_pts", "Loser":"loser", "Losing Pts":"loser_pts", "MVP":"mvp", "Stadium":"stadium", "City":"city", "State":"state"})
cleaned_sb_df.reset_index(drop=True)
cleaned_sb_df.head()

,SB,attendance,winner,winning_pts,loser,loser_pts,mvp,stadium,city,state
0,I,61946,Green Bay Packers,35,Kansas City Chiefs,10,Bart Starr,Memorial Coliseum,Los Angeles,California
1,II,75546,Green Bay Packers,33,Oakland Raiders,14,Bart Starr,Orange Bowl,Miami,Florida
2,III,75389,New York Jets,16,Baltimore Colts,7,Joe Namath,Orange Bowl,Miami,Florida
3,IV,80562,Kansas City Chiefs,23,Minnesota Vikings,7,Len Dawson,Tulane Stadium,New Orleans,Louisiana
4,V,79204,Baltimore Colts,16,Dallas Cowboys,13,Chuck Howley,Orange Bowl,Miami,Florida

In [5]:
connection_string = "postgres:chicago1023@localhost:5432/project2"
engine = create_engine(f'postgresql://{connection_string}')

In [6]:
# Confirm tables
engine.table_names()

['superbowl']

In [7]:
cleaned_sb_df.to_sql(name='superbowl', con=engine, if_exists='append', index=false)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "index" of relation "superbowl" does not exist
LINE 1: INSERT INTO superbowl (index, "SB", attendance, winner, winn...
                               ^

[SQL: INSERT INTO superbowl (index, "SB", attendance, winner, winning_pts, loser, loser_pts, mvp, stadium, city, state) VALUES (%(index)s, %(SB)s, %(attendance)s, %(winner)s, %(winning_pts)s, %(loser)s, %(loser_pts)s, %(mvp)s, %(stadium)s, %(city)s, %(state)s)]
[parameters: ({'index': 0, 'SB': 'I', 'attendance': 61946, 'winner': 'Green Bay Packers', 'winning_pts': 35, 'loser': 'Kansas City Chiefs', 'loser_pts': 10, 'mvp': 'Bart Starr', 'stadium': 'Memorial Coliseum', 'city': 'Los Angeles', 'state': 'California'}, {'index': 1, 'SB': 'II', 'attendance': 75546, 'winner': 'Green Bay Packers', 'winning_pts': 33, 'loser': 'Oakland Raiders', 'loser_pts': 14, 'mvp': 'Bart Starr', 'stadium': 'Orange Bowl', 'city': 'Miami', 'state': 'Florida'}, {'index': 2, 'SB': 'III', 'attendance': 75389, 'winner': 'New York Jets', 'winning_pts': 16, 'loser': 'Baltimore Colts', 'loser_pts': 7, 'mvp': 'Joe Namath', 'stadium': 'Orange Bowl', 'city': 'Miami', 'state': 'Florida'}, {'index': 3, 'SB': 'IV', 'attendance': 80562, 'winner': 'Kansas City Chiefs', 'winning_pts': 23, 'loser': 'Minnesota Vikings', 'loser_pts': 7, 'mvp': 'Len Dawson', 'stadium': 'Tulane Stadium', 'city': 'New Orleans', 'state': 'Louisiana'}, {'index': 4, 'SB': 'V', 'attendance': 79204, 'winner': 'Baltimore Colts', 'winning_pts': 16, 'loser': 'Dallas Cowboys', 'loser_pts': 13, 'mvp': 'Chuck Howley', 'stadium': 'Orange Bowl', 'city': 'Miami', 'state': 'Florida'}, {'index': 5, 'SB': 'VI', 'attendance': 81023, 'winner': 'Dallas Cowboys', 'winning_pts': 24, 'loser': 'Miami Dolphins', 'loser_pts': 3, 'mvp': 'Roger Staubach', 'stadium': 'Tulane Stadium', 'city': 'New Orleans', 'state': 'Louisiana'}, {'index': 6, 'SB': 'VII', 'attendance': 90182, 'winner': 'Miami Dolphins', 'winning_pts': 14, 'loser': 'Washington Redskins', 'loser_pts': 7, 'mvp': 'Jake Scott', 'stadium': 'Memorial Coliseum', 'city': 'Los Angeles', 'state': 'California'}, {'index': 7, 'SB': 'VIII', 'attendance': 71882, 'winner': 'Miami Dolphins', 'winning_pts': 24, 'loser': 'Minnesota Vikings', 'loser_pts': 7, 'mvp': 'Larry Csonka', 'stadium': 'Rice Stadium', 'city': 'Houston', 'state': 'Texas'}  ... displaying 10 of 52 total bound parameter sets ...  {'index': 50, 'SB': 'LI ', 'attendance': 70807, 'winner': 'New England Patriots', 'winning_pts': 34, 'loser': 'Atlanta Falcons', 'loser_pts': 28, 'mvp': 'Tom Brady', 'stadium': 'NRG Stadium', 'city': 'Houston', 'state': 'Texas'}, {'index': 51, 'SB': 'LII', 'attendance': 67612, 'winner': 'Philadelphia Eagles', 'winning_pts': 41, 'loser': 'New England Patriots', 'loser_pts': 33, 'mvp': 'Nick Foles', 'stadium': 'U.S. Bank Stadium', 'city': 'Minneapolis', 'state': 'Minnesota'})]
(Background on this error at: http://sqlalche.me/e/f405)